adding to_bin_str function
ucsc-vama/firrtl-sig pull request #2
Opened 2022-11-24 05:26 UTC by MSPDUTTA

Added to_bin_str function and two tests

2022-11-29 00:59 UTC, sbeamer requested changes

2022-11-29 00:59 UTC, sbeamer commented on uint.h
> +   std::string to_bin_str(std::ostream& os) const {
Perhaps this should take no arguments

2022-11-29 00:59 UTC, sbeamer commented on tester.cc
> +UInt<192> abcdu("0xffffffffffffffff0000000000000000ff1f1f1f1f1f1f1f");
Could you use the existing test variables (e.g. a16u, b64u, etc...) instead of declaring new ones?

2022-11-29 00:59 UTC, sbeamer commented on tester.cc
> +#include <fstream>
I don't believe firrtl-sig needs to deal with files (including following lines).

2022-12-05 21:21 UTC, MSPDUTTA commented on tester.cc
> +UInt<192> abcdu("0xffffffffffffffff0000000000000000ff1f1f1f1f1f1f1f");
Yes

2022-12-05 21:51 UTC, sbeamer approved these changes

2022-12-05 21:52 UTC, merged